name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - id: checkout
          name: Checkout
          uses: actions/checkout@v4
        - id: setup-bun
          name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - id: install-deps
          name: Install dependencies
          run: |
            bun install -g uglify-js shx
            bun install
        - id: build
          name: Run compress
          run: |
            bun run compress
  